Implicit tiling
CesiumGS/cdb-to-3dtiles pull request #41
Opened 2021-02-08 23:27 UTC by ErixenCruz

2021-02-20 03:01 UTC, ErixenCruz commented
All that is left to do is fix some hard coding of URIs in subtree, tweak morton index calculation to account for variable subtree level, better comments and documentation and tests, and double check when running full Yemen. Eventually multi-content

2021-03-03 14:49 UTC, sanjeetsuhag requested changes
I did an initial pass, just looking at the diffs.

2021-03-03 14:49 UTC, sanjeetsuhag commented on CDBTo3DTiles/CMakeLists.txt
> +message("This is from line 38:" ${VAR})
This debug statement should be removed.

2021-03-03 14:49 UTC, sanjeetsuhag commented on CDBTo3DTiles/include/CDBTo3DTiles.h
> +// #include "ConverterImpl.h"
Remove unnecessary comments.

2021-03-03 14:49 UTC, sanjeetsuhag commented on CDBTo3DTiles/include/CDBTo3DTiles.h
> +    // struct Impl;
Remove unnecessary comments.

2021-03-03 14:49 UTC, sanjeetsuhag commented on Core/src/FileUtil.cpp
> +namespace AGI
Change this namespace to `CDBTo3DTiles`

2021-03-03 14:49 UTC, sanjeetsuhag commented on Core/include/FileUtil.h
> +namespace AGI
Change namespace to `CDBTo3DTiles`

2021-03-03 14:49 UTC, sanjeetsuhag commented on CDBTo3DTiles/src/TileFormatIO.cpp
> +        // TODO fix .. here
Is this fix in? Can this comment be removed?

2021-03-03 14:49 UTC, sanjeetsuhag commented on CDBTo3DTiles/src/TileFormatIO.cpp
> +      tilesetJson["extensionsUsed"] = nlohmann::json::array();
You can add the value in the constructor:

```suggestion
      tilesetJson["extensionsUsed"] = nlohmann::json::array({ "3DTILES_implicit_tiling" });
```

2021-03-03 14:49 UTC, sanjeetsuhag commented on CDBTo3DTiles/src/CDBTo3DTiles.cpp
> +          // TODO check this logic for multi subtree (buffers)
Is this fix in?

2021-03-03 14:49 UTC, sanjeetsuhag commented on CDBTo3DTiles/src/CDBTile.h
> +    std::string getLevelWithNoZeroPaddingInFilename() const noexcept;
Add unit tests for the new functions in this file.

2021-03-05 18:59 UTC, sanjeetsuhag requested changes
I'll do a more thorough review of the test cases after the `SEGFAULT` is fixed.

2021-03-05 18:59 UTC, sanjeetsuhag commented on CDBTo3DTiles/src/CDBTo3DTiles.cpp
> +            // combineTilesetJson(tileset.second, combinedTilesetsRegions[tileset.first], fs);
Can these be removed?

2021-03-05 18:59 UTC, sanjeetsuhag commented on Core/include/FileUtil.h
> +} // namespace AGI
Replace AGI namespace

2021-03-05 18:59 UTC, sanjeetsuhag commented on Core/src/FileUtil.cpp
> +} // namespace AGI
Replace AGI namespace

2021-03-09 22:30 UTC, sanjeetsuhag commented on CDBTo3DTiles/src/ConverterImpl.cpp
> +  // TODO the rref and uref need to be with respect to subtree, not larger tree
Is this still `TODO`?

2021-03-09 22:31 UTC, sanjeetsuhag commented on CDBTo3DTiles/src/ConverterImpl.cpp
> +// TODO remove this function?
Is this still `TODO`?

2021-03-09 22:31 UTC, sanjeetsuhag commented on Tests/CombineTilesetsTest.cpp
> +  // TODO write function for creating buffer given subtree level
Is this still `TODO`?

2021-03-10 16:17 UTC, sanjeetsuhag approved these changes

2021-03-11 15:53 UTC, merged